[Package]
Name = "Laboratory"
Version = "0.1.0"
Description = "Developing language and syntax"
License = "MIT"
Authors = ["Ivan Muzyka"]
Edition = "2025"

[Build]
Target = "x86_64"
OptLevel = "Release"

[Profile.Debug]
OptLevel = 0
Output = "Bin/Debug"

[Profile.Release]
OptLevel = 3
Output = "Bin/Release"

[Dependencies]
Std = "0.1.0"

[Scripts]
Build = "rux build"
Test = "rux test"
